#!/usr/bin/env php

<?php 
// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

use dynamikaweb\api\OneDocApi;

$config = [
    'id' => '1doc-test',
    'basePath' => __DIR__,
    'controllerNamespace' => 'app',
    'components' => [
        'session' => [
            'class' => 'yii\web\Session',
            'name' => 'my-session',
        ],
        'OneDocApi' => [
            'class' => 'dynamikaweb\api\OneDocApi',
            'client_auth' => '25F3BA66',
            'token' => '0w99djasd9hj2818dh182hd8ashd8h2kskdja',
            'secret' => 'j19s8dyu82du0asj028ucuudsd9sad828y81',
        ]
    ],
    'params' => [],
];

$application = new yii\console\Application($config);


print_r (Yii::$app->OneDocApi);//->getRequest(true) );



//$exitCode = $application->run();
//exit($exitCode);